name: "CI"

on:
  push

jobs:
  action-validator:
    name: "Validate ${{ matrix.workflow-file }}"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      # actions/checkout
      contents: read

    strategy:
      fail-fast: false
      matrix:
        workflow-file:
          - CI.yml # self-validation.
          - validate.yml
          - instrumentation.yml

    steps:
      - name: "Checkout ${{ github.ref }} branch in ${{ github.repository }} repository."
        uses: actions/checkout@v4

      - name: "Install action-validator."
        working-directory: action-validator
        run: npm install

      - name: "Validate workflow file."
        working-directory: action-validator
        env:
          WORKFLOW_FILE: ${{ github.workspace }}/.github/workflows/${{ matrix.workflow-file }}
        run: npx --no-install action-validator "${WORKFLOW_FILE}"
