name: "CI"

on:
  push

jobs:
  action-validator:
    name: "Validate ${{ matrix.workflow-file }}"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      # actions/checkout
      contents: read

    strategy:
      fail-fast: false
      matrix:
        workflow-file:
          - ci.yml # self-validation.
          - validate.yml
          - instrumentation.yml

    steps:
      - name: "Checkout ${{ github.ref }} branch in ${{ github.repository }} repository."
        uses: actions/checkout@v4

      - name: "Validate workflow file."
        env:
          WORKFLOW_FILE: ${{ github.workspace }}/.github/workflows/${{ matrix.workflow-file }}
        run: npm exec --package=@action-validator/cli --no -- action-validator "${WORKFLOW_FILE}"
