name: "🦺 Validation"

on:
  workflow_call:
    inputs:

      gradle:
        description: "This project is not Gradle-based."
        type: boolean
        required: false
        default: true

jobs:

  gradle-wrapper:
    name: "Gradle Wrapper"
    if: ${{ inputs.gradle }}
    runs-on: ubuntu-latest
    timeout-minutes: 2

    permissions:
      # actions/checkout
      contents: read

    steps:

      - name: "Checkout ${{ github.ref }} ref in ${{ github.repository }} repository."
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: "Validate Gradle Wrapper JARs."
        uses: gradle/actions/wrapper-validation@v4


  ghlint:
    name: "GitHub Workflows (ghlint)"
    runs-on: ubuntu-latest
    timeout-minutes: 2

    permissions:
      # actions/checkout
      contents: read
      # github/codeql-action/upload-sarif
      security-events: write
      # github/codeql-action/upload-sarif in private repositories / internal organizations.
      actions: read

    steps:

      - name: "Checkout ${{ github.ref }} ref in ${{ github.repository }} repository."
        uses: actions/checkout@v4

      - name: "Run GH-Lint validator."
        id: ghlint
        uses: TWiStErRob/net.twisterrob.ghlint@v0.5.0

      - name: "Upload 'GH-Lint Results' artifact."
        if: ${{ success() || failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: 'GH-Lint Results'
          if-no-files-found: error
          path: ${{ steps.ghlint.outputs.sarif-report }}

      - name: "Publish 'GH-Lint' GitHub Code Scanning analysis."
        if: ${{ success() || failure() }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          checkout_path: ${{ github.workspace }}
          sarif_file: ${{ steps.ghlint.outputs.sarif-report }}


  renovate:
    name: "Renovate"
    runs-on: ubuntu-latest
    timeout-minutes: 3
    
    permissions:
      # actions/checkout
      contents: read

    env:
      RENOVATE_VERSION: '38.57.0' # renovate

    steps:

      - name: "Cache NPX"
        uses: actions/cache@v4
        with:
          key: npx-${{ github.workflow }}-${{ github.job }}-${{ env.RENOVATE_VERSION }}
          path: |
            ~/.npm/_npx

      - name: "Checkout ${{ github.ref }} ref in ${{ github.repository }} repository."
        uses: actions/checkout@v4

      - name: "Run renovate-config-validator on repository configuration."
        shell: bash
        run: >
          npx
          --yes
          --package "renovate@${RENOVATE_VERSION}"
          --
          renovate-config-validator
          --strict
          .github/renovate.json5
