name: "🦺 Validation"

on:
  workflow_call

jobs:

  gradle-wrapper:
    name: "Gradle Wrapper"
    runs-on: ubuntu-latest
    timeout-minutes: 2

    permissions:
      # actions/checkout
      contents: read

    steps:

      - name: "Checkout ${{ github.ref }} branch in ${{ github.repository }} repository."
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: "Validate Gradle Wrapper JARs."
        uses: gradle/wrapper-validation-action@v2
        with:
          min-wrapper-count: 0


  ghlint:
    name: "GitHub Workflows (ghlint)"
    runs-on: ubuntu-latest
    timeout-minutes: 2

    permissions:
      # actions/checkout
      contents: read
      # github/codeql-action/upload-sarif
      security-events: write
      # github/codeql-action/upload-sarif in private repositories / internal organizations.
      actions: read

    steps:

      - name: "Checkout ${{ github.ref }} branch in ${{ github.repository }} repository."
        uses: actions/checkout@v4

      - name: "Download validator."
        working-directory: ${{ runner.temp }}
        env:
          GHLINT_VERSION: '0.3.0'
        shell: bash
        run: |
          curl --silent --show-error --location --remote-name \
           https://github.com/TWiStErRob/net.twisterrob.ghlint/releases/download/v${GHLINT_VERSION}/ghlint.jar
          chmod +x ghlint.jar

      - name: "Run validator."
        env:
          FILES: ${{ steps.files.outputs.result }}
        shell: bash
        run: |
          "${{ runner.temp }}/ghlint.jar" --verbose --sarif=report.sarif.json .github/workflows/*.yml

      - name: "Upload 'GH-Lint Results' artifact."
        if: ${{ success() || failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: 'GH-Lint Results'
          if-no-files-found: error
          path: report.sarif.json

      - name: "Publish 'GH-Lint' GitHub Code Scanning analysis."
        if: ${{ success() || failure() }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          checkout_path: ${{ github.workspace }}
          sarif_file: report.sarif.json
