name: "🦺 Validation"

on:
  workflow_call

jobs:

  gradle-wrapper:
    name: "Gradle Wrapper"
    runs-on: ubuntu-latest
    timeout-minutes: 2

    permissions:
      # actions/checkout
      contents: read

    steps:

      - name: "Checkout ${{ github.ref }} branch in ${{ github.repository }} repository."
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: "Validate Gradle Wrapper JARs."
        uses: gradle/wrapper-validation-action@v2
        with:
          min-wrapper-count: 0


  ghlint:
    name: "GitHub Workflows (ghlint)"
    runs-on: ubuntu-latest
    timeout-minutes: 2

    permissions:
      # actions/checkout
      contents: read
      # github/codeql-action/upload-sarif
      security-events: write
      # github/codeql-action/upload-sarif in private repositories / internal organizations.
      actions: read

    steps:

      - name: "Checkout ${{ github.ref }} branch in ${{ github.repository }} repository."
        uses: actions/checkout@v4

      - name: "Run GH-Lint validator."
        id: ghlint
        uses: TWiStErRob/net.twisterrob.ghlint@v0.3.0
        with:
          

      - name: "Upload 'GH-Lint Results' artifact."
        if: ${{ success() || failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: 'GH-Lint Results'
          if-no-files-found: error
          path: ${{ steps.ghlint.outputs.sarif-report }}

      - name: "Publish 'GH-Lint' GitHub Code Scanning analysis."
        if: ${{ success() || failure() }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          checkout_path: ${{ github.workspace }}
          sarif_file: ${{ steps.ghlint.outputs.sarif-report }}
